version: '3.7'

services:

  minio:
    hostname: minio
    image: 'minio/minio:latest'
    container_name: minio
    ports:
      - "9001:9001"
      - "9000:9000"
    command: ["server", "/data", "--console-address", ":9001"]
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin

  init-minio:
    build:
      context: ./init-minio
    depends_on:
      - minio

  generate-data:
    build:
      context: ./generate-data
    depends_on:
      - init-minio
      - minio

  data-transform:
    build:
      context: ./data-transform
    depends_on:
      - generate-data
      - init-minio
      - minio

volumes:
  minio:



