version: '3.8'

services:
  minio:
    image: cdaprod/cda-minio:latest
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app_network
    secrets:
      - minio_access_key
      - minio_secret_key

  weaviate:
    image: cdaprod/cda-weaviate:latest
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      QUERY_DEFAULTS_LIMIT: 25
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'backup-s3, text2vec-openai'
      BACKUP_S3_BUCKET: 'weaviate-backups'
      BACKUP_S3_ENDPOINT: 'minio:9000'
      BACKUP_S3_ACCESS_KEY_ID: 'minio'
      BACKUP_S3_SECRET_ACCESS_KEY: 'minio123'
      BACKUP_S3_USE_SSL: 'false'
      CLUSTER_HOSTNAME: 'node1'
    volumes:
      - weaviate_data:/var/lib/weaviate
    networks:
      - app_network
    depends_on:
      - minio

  nginx:
    image: cdaprod/cda-nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: overlay

volumes:
  minio_data:
  weaviate_data:

secrets:
  minio_access_key:
    external: true
  minio_secret_key:
    external: true
