coordinator=false
http-server.http.port=8080
discovery.uri=http://loadgen-09a:8080
internal-communication.shared-secret=asdkjfdadjasd;fdjaajdjd
query.max-memory-per-node=280GB
query.max-memory=2000GB
